[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "MithunKumarRajak",email = "148649863+MithunKumarRajak@users.noreply.github.com"}
]
requires-python = ">=3.10"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
