"""Advanced models: multilingual, bias, semantic match

Revision ID: 46b39fab543a
Revises: 97a323ec476e
Create Date: 2026-05-05 04:47:41.763014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46b39fab543a'
down_revision: Union[str, Sequence[str], None] = '97a323ec476e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bias_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_type', sa.String(length=50), nullable=True),
    sa.Column('sensitive_feature', sa.String(length=50), nullable=True),
    sa.Column('demographic_parity_difference', sa.Float(), nullable=True),
    sa.Column('equalized_odds_difference', sa.Float(), nullable=True),
    sa.Column('bias_assessment', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('raw_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_model_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('trained_at', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resume_analyses', sa.Column('job_description_text', sa.Text(), nullable=True))
    op.add_column('resume_analyses', sa.Column('semantic_score', sa.Float(), nullable=True))
    op.add_column('resume_analyses', sa.Column('keyword_overlap_score', sa.Float(), nullable=True))
    op.add_column('resume_analyses', sa.Column('combined_score', sa.Float(), nullable=True))
    op.add_column('resume_analyses', sa.Column('semantic_model_used', sa.String(length=100), nullable=True))
    op.add_column('resume_analyses', sa.Column('predicted_category', sa.String(length=100), nullable=True))
    op.add_column('resume_analyses', sa.Column('prediction_confidence', sa.Float(), nullable=True))
    op.add_column('resume_analyses', sa.Column('model_version', sa.String(length=20), nullable=True))
    op.add_column('resume_analyses', sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resume_analyses', sa.Column('explanation_summary', sa.Text(), nullable=True))
    op.add_column('resume_analyses', sa.Column('detected_language', sa.String(length=10), nullable=True))
    op.add_column('resume_analyses', sa.Column('bias_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resume_analyses', sa.Column('gender_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resume_analyses', sa.Column('age_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resume_analyses', sa.Column('analysis_duration_ms', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('resumes', sa.Column('language_confidence', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('has_hindi_content', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'has_hindi_content')
    op.drop_column('resumes', 'language_confidence')
    op.drop_column('resumes', 'language')
    op.drop_column('resume_analyses', 'analysis_duration_ms')
    op.drop_column('resume_analyses', 'age_indicators')
    op.drop_column('resume_analyses', 'gender_indicators')
    op.drop_column('resume_analyses', 'bias_flags')
    op.drop_column('resume_analyses', 'detected_language')
    op.drop_column('resume_analyses', 'explanation_summary')
    op.drop_column('resume_analyses', 'explanation')
    op.drop_column('resume_analyses', 'model_version')
    op.drop_column('resume_analyses', 'prediction_confidence')
    op.drop_column('resume_analyses', 'predicted_category')
    op.drop_column('resume_analyses', 'semantic_model_used')
    op.drop_column('resume_analyses', 'combined_score')
    op.drop_column('resume_analyses', 'keyword_overlap_score')
    op.drop_column('resume_analyses', 'semantic_score')
    op.drop_column('resume_analyses', 'job_description_text')
    op.drop_table('custom_model_configs')
    op.drop_table('bias_audit_logs')
    # ### end Alembic commands ###
