"""add_phase2_tables

Revision ID: 97a323ec476e
Revises: 
Create Date: 2026-05-05 03:32:36.958967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97a323ec476e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('recruiter_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='bulkjobstatus'), nullable=False),
    sa.Column('total_resumes', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_jobs_job_id'), 'bulk_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_bulk_jobs_recruiter_id'), 'bulk_jobs', ['recruiter_id'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_email'), 'candidate_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=False)
    op.create_table('resume_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('job_description_id', sa.String(length=36), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('keyword_match_score', sa.Float(), nullable=False),
    sa.Column('skills_match_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ats_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimization_tips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_description_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_analyses_job_description_id'), 'resume_analyses', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_resume_analyses_resume_id'), 'resume_analyses', ['resume_id'], unique=False)
    op.create_table('email_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_email', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.Enum('shortlisted', 'rejected', 'on_hold', 'interview_invite', name='notificationtype'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('resume_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_analysis_id'], ['resume_analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_notifications_candidate_email'), 'email_notifications', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_email_notifications_resume_analysis_id'), 'email_notifications', ['resume_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_notifications_resume_analysis_id'), table_name='email_notifications')
    op.drop_index(op.f('ix_email_notifications_candidate_email'), table_name='email_notifications')
    op.drop_table('email_notifications')
    op.drop_index(op.f('ix_resume_analyses_resume_id'), table_name='resume_analyses')
    op.drop_index(op.f('ix_resume_analyses_job_description_id'), table_name='resume_analyses')
    op.drop_table('resume_analyses')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_email'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_bulk_jobs_recruiter_id'), table_name='bulk_jobs')
    op.drop_index(op.f('ix_bulk_jobs_job_id'), table_name='bulk_jobs')
    op.drop_table('bulk_jobs')
    # ### end Alembic commands ###
